spring.application.name=bankingapplication


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DatasourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfigutration